import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const inter = localFont({ 
  src: [
    { path: '../../public/fonts/Inter-Regular.ttf', weight: '400' },
    { path: '../../public/fonts/Inter-Bold.ttf', weight: '700' },
    // Add more font files as needed for other weights/styles
  ],
  variable: '--font-inter', // If you're using variable fonts
});

const myFont = localFont({ src: '../../public/fonts/Poppins-Regular.ttf' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${myFont.className}`}>
        {children}
      </body>
    </html>
  );
}
